# Generated by Django 4.2 on 2023-04-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=15, null=True, verbose_name='Transaction')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(max_length=120, verbose_name='Payment_Method')),
            ],
        ),
    ]
