# Generated by Django 4.2 on 2023-04-09 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprogress',
            name='applicants',
            field=models.ManyToManyField(related_name='Applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderprogress',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderprogress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.clientorder'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='order_category',
            field=models.ManyToManyField(related_name='Order_Category', to='user.userinterest'),
        ),
    ]
