# Generated by Django 4.2 on 2023-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='is_active_order',
            field=models.BooleanField(default=True),
        ),
    ]
