# Generated by Django 4.2 on 2023-05-20 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_clientorder_is_active_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprogress',
            name='applicants',
            field=models.ManyToManyField(null=True, related_name='Applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderprogress',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
