# Generated by Django 4.2 on 2023-05-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderprogress_applicants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='order_files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.clientorder')),
            ],
        ),
    ]
